#ifndef LO21___PRINTEMPS_2021___PROJET_CELLULUT_OUTILS_H
#define LO21___PRINTEMPS_2021___PROJET_CELLULUT_OUTILS_H

int char_to_int(char * c);

#endif //LO21___PRINTEMPS_2021___PROJET_CELLULUT_OUTILS_H
